services:
  squid-bot:
    build:
      context: .
    container_name: squid-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - default
    volumes:
      - ${SQUID_DIR}:/app/squid
